name: transcriptions-viewer
services:
    postgres:
        container_name: postgres
        image: postgres:16-alpine
        restart: unless-stopped
        ports: 
            - '5432:5432'
        volumes:
            - "./docker/db/data:/var/lib/postgresql/data"
            - "./docker/init:/docker-entrypoint-initdb.d"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: development
    minio:
        container_name: minio
        image: minio/minio
        restart: unless-stopped
        ports:   
            - "19002:19002"
            - "19003:19003"
        volumes:
            - "./docker/minio_storage:/data"
        environment:
            MINIO_ROOT_USER: root
            MINIO_ROOT_PASSWORD: password
        command: server --address ":19002" --console-address ":19003" /data