services:
    postgres:
        container_name: transcriptions-db
        image: postgres:16-alpine
        restart: unless-stopped
        ports: 
            - '5432:5432'
        volumes:
            - "./docker/db/data:/var/lib/postgresql/data"
            - "./docker/init:/docker-entrypoint-initdb.d"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: development